apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "driftguard.fullname" . }}
  labels:
    {{- include "driftguard.labels" . | nindent 4 }}
    track: stable
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "driftguard.selectorLabels" . | nindent 6 }}
      track: stable
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  template:
    metadata:
      labels:
        {{- include "driftguard.selectorLabels" . | nindent 8 }}
        track: stable
    spec:
      serviceAccountName: {{ include "driftguard.fullname" . }}
      securityContext:
        {{- include "driftguard.podSecurityContext" . | nindent 8 }}
      containers:
        - name: app
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 8000
          env:
            {{- range $name, $value := .Values.env }}
            - name: {{ $name }}
              value: {{ $value | quote }}
            {{- end }}
          {{- include "driftguard.probes" . | nindent 10 }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          securityContext:
            {{- include "driftguard.containerSecurityContext" . | nindent 12 }}
          volumeMounts:
            - name: tmp
              mountPath: /tmp
      volumes:
        - name: tmp
          emptyDir: {}
